default_config:

logger:
  default: info
  logs: {}
    # pymodbus: debug
    # custom_components.idm_heatpump: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
